#!/bin/bash

chmod 775 ramdisk/
chmod 777 ramdisk/etc
chmod 771 ramdisk/data
chmod 755 ramdisk/acct
chmod 755 ramdisk/proc
chmod 755 ramdisk/firmware
chmod 750 ramdisk/init.miui.google_revenue_share.rc
chmod 755 ramdisk/bt_firmware
chmod 755 ramdisk/res
chmod 755 ramdisk/res/images
chmod 755 ramdisk/res/images/charger
chmod 644 ramdisk/res/images/charger/Battery_red2.png
chmod 644 ramdisk/res/images/charger/4.png
chmod 644 ramdisk/res/images/charger/Battery_green3.png
chmod 644 ramdisk/res/images/charger/5.png
chmod 644 ramdisk/res/images/charger/3.png
chmod 644 ramdisk/res/images/charger/Battery_red1.png
chmod 644 ramdisk/res/images/charger/Battery.png
chmod 644 ramdisk/res/images/charger/battery_fail.png
chmod 644 ramdisk/res/images/charger/battery_scale.png
chmod 644 ramdisk/res/images/charger/0.png
chmod 644 ramdisk/res/images/charger/2.png
chmod 644 ramdisk/res/images/charger/7.png
chmod 644 ramdisk/res/images/charger/8.png
chmod 644 ramdisk/res/images/charger/1.png
chmod 644 ramdisk/res/images/charger/9.png
chmod 644 ramdisk/res/images/charger/Battery_0.png
chmod 644 ramdisk/res/images/charger/6.png
chmod 644 ramdisk/res/images/charger/10.png
chmod 644 ramdisk/res/images/charger/Battery_green2.png
chmod 644 ramdisk/res/images/charger/Battery_green1.png
chmod 755 ramdisk/dsp
chmod 755 ramdisk/dev
chmod 777 ramdisk/d
chmod 755 ramdisk/mnt
chmod 755 ramdisk/sys
chmod 777 ramdisk/charger
chmod 777 ramdisk/sdcard
chmod 750 ramdisk/init.miui.nativedebug.rc
chmod 750 ramdisk/init.miui.early_boot.sh
chmod 755 ramdisk/system
chmod 750 ramdisk/init.usb.rc
chmod 750 ramdisk/init.zygote64_32.rc
chmod 500 ramdisk/config
chmod 777 ramdisk/default.prop
chmod 770 ramdisk/cache
chmod 755 ramdisk/oem
chmod 750 ramdisk/init
chmod 750 ramdisk/init.usb.configfs.rc
chmod 750 ramdisk/init.zygote32.rc
chmod 750 ramdisk/init.miui.post_boot.sh
chmod 750 ramdisk/init.miui.cust.rc
chmod 755 ramdisk/persist
chmod 750 ramdisk/sbin
chmod 750 ramdisk/sbin/charger
chmod 777 ramdisk/sbin/ueventd
chmod 664 ramdisk/sbin/restart.sh
chmod 777 ramdisk/sbin/watchdogd
chmod 644 ramdisk/ueventd.rc
chmod 750 ramdisk/init.rc
chmod 750 ramdisk/init.environ.rc
chmod 750 ramdisk/init.miui.google_revenue_share_v2.rc
chmod 777 ramdisk/bugreports
chmod 750 ramdisk/init.recovery.qcom.rc
chmod 755 ramdisk/vendor
chmod 750 ramdisk/init.recovery.hardware.rc
chmod 750 ramdisk/init.miui.rc
chmod 751 ramdisk/storage
